apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: orc-letsencrypt-issuer
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: vasyakrg@gmail.com
    # Name of a secret used to store the ACME account private key from step 3
    privateKeySecretRef:
      name: orc-letsencrypt-private-key
    # Enable the HTTP-01 challenge provider
    solvers:
    # An empty selector will 'match' all Certificate resources that
    # reference this Issuer.
    - selector: {}
      http01:
        ingress:
          class: nginx
